name = "sbl"
uuid = "cb6d40ba-6026-4b87-a3e3-c46a1d25166d"
authors = ["Andreas Hildebrandt <andreas.hildebrandt@uni-mainz.de> and contributors"]
version = "0.1.0"

[deps]
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
StructTypes = "1.2"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
